# Docker Compose Override for Development
# Use with: docker-compose up (automatically applies overrides)

version: '3.8'

services:
  api:
    environment:
      # Development settings
      - APP_ENV=development
      - DEBUG=true
      - WORKERS=1
      
      # Disable authentication for easier development
      - REQUIRE_API_KEYS=false
      
      # Relaxed rate limiting
      - DEFAULT_RATE_LIMIT_PER_MINUTE=1000
      
      # Development CORS
      - API_CORS_ORIGINS=["*"]
      
    volumes:
      # Mount source code for live reload
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      
    # Override command for development with auto-reload
    command: >
      bash -c "
        echo 'Starting in development mode with auto-reload...'
        uvicorn src.api.main:create_app --factory --host 0.0.0.0 --port 8000 --reload
      "
    
    # Development resource limits (more relaxed)
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

  redis:
    # Expose Redis port for local development tools
    ports:
      - "6379:6379"
      
    # Development Redis config (less strict)
    command: >
      redis-server 
      --maxmemory 512mb
      --save ""

  # Disable worker in development (API handles everything)
  worker:
    deploy:
      replicas: 0